version: '3'
services:
  backend-test:
    container_name: ms-ocr
    build:
      context: ./flask
      dockerfile: Dockerfile
    environment:
      FLASK_DEBUG: true
      FLASK_APP: "app:getFlaskApp"
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_RELOAD: 1
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 32000
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: intelnexoDB
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - ./flask:/usr/src/app
  frontend:
    container_name: cw-frontend
    build:
        context: ./intelnexo
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./intelnexo:/app
  db:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: intelnexoDB
      MYSQL_ROOT_PASSWORD: root
    volumes:
      -  mysql-data:/var/lib/mysql
      - ./insert_data.sql:insert_data.sql
    
volumes:
  mysql-data: